### ISSUE TITLE
Java package / namespace

### ISSUE THREAD

**Issue by kvr000** [novotnyradek/fred-client#1]
One of the most critical things in Java is to make the package name unique, in order to work correctly in environment which consumes tons of 3rd-party packages.

There is a convention to follow the company DNS domain in reverse order, followed by department, project name and subsequent component packages (can omit what is not applicable here, except the first and third part). Therefore, instead of using "fred.client" which can conflict with any other "fred" in the world, the package should look like "cz.active24.registration.fred.client" or "cz.nic.registration.fred.client" or "cz.nic.fred.client" etc. The convention: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

This is especially critical as (assuming) the goal of the project is become official client for Java.

**Comment by novotnyradek** [comment]
Hello, thank you very much for your opinion. We were solving groupId a lot and forget about package name. Of course you are right. No, when client is officially accepted by CZ.NIC, the groupId and also package name is "cz.active24.client.fred".
