### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tanzanian** [novotnyradek/fred-client#2]
Dear Sir,
For someone who is new to JAVA, can you advice 

1. how this can be installed for a new registrar? Is it to be installed on their hosting server or on their local machine?

2. Is there any demo where the usage can be tested?

3. Does anyone provide installation services?

**Comment by novotnyradek** [comment]
Hello,

1) you can use it as Maven dependency or .jar file to your system. It is just client providing connection to FRED system (supported by CZ.NIC, not myself),
2) you can call various commands right from the Main method against test instance of FRED,
3) for FRED the installation services are provided by CZ.NIC.

Have a nice day
R.
